services:
    tekkl.listeners.kernel.response.allow_origin:
        class: Tekkl\Bundle\AppBundle\EventListener\KernelResponse\AllowXOrigin
        arguments: ["*", "^/api", "Authorization,Refresh-Token"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }