services:
    tekkl.listeners.kernel.response.allow_origin:
        class: Tekkl\Bundle\AppBundle\EventListener\KernelResponse\AllowXOrigin
        arguments: ["*", "^/api", "Authorization,Refresh-Token,X-PINGOTHER,Content-Type", "GET,PUT,POST,DELETE"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }