services:
    tekkl.mailer:
        class: Tekkl\Bundle\AppBundle\Service\Mailer
        arguments: ['@mailer']
    tekkl.util.inflector:
        class: Tekkl\Bundle\AppBundle\Util\Inflector\RestInflector
    tekkl.listeners.kernel.request.json_request_data:
        class: Tekkl\Bundle\AppBundle\EventListener\KernelRequest\JsonRequestData
        arguments: [["POST", "PUT", "PATCH"], "^/api"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 255 }