imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: components/doctrine.yml }
    - { resource: components/twig.yml }
    - { resource: components/swift.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: { enabled: false }
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

tekkl_app:
    app_name: '%app_name%' 
    app_email: '%app_email%'
    host: '%app_host%'
    path: '%app_base_path%'
    use_ssl: '%app_use_ssl%'

tekkl_user:
    registration:
        confirmation:
            enabled: true

tekkl_facebook:
    app_id: '%facebook_app_id%'
    app_secret: '%facebook_app_secret%'
    version: 'v2.9'

# Configuration of the various bundles this app uses
fos_rest:
    view:
        empty_content: 204
        view_response_listener: 'force'
    format_listener:
        enabled: true
        rules:
            - { path: '^/api', priorities: ['json'] }
            - { path: '^/', priorities: ['html'] }
    exception:
        enabled: true
    service:
        inflector: tekkl.util.inflector

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: Tekkl\Bundle\UserBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
        form:
            name: ''
    resetting:
        form:
            name: 'reset_form'

gesdinet_jwt_refresh_token:
    ttl: 2592000
    user_provider: fos_user.user_provider.username_email
    methods:
        request_header:
            enabled: true
        request_body:
            enabled: false
        cookie:
            enabled: false

lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'

doctrine_migrations:
    dir_name: "%kernel.root_dir%/Tekkl/Migrations"
    namespace: Tekkl\Migrations
    table_name: migration_versions
    name: TEKKL Migrations

services:
    _defaults:
        autowire: true
        autoconfigure: true

