gesdinet_jwt_refresh_token:
    ttl: 2592000
    user_provider: fos_user.user_provider.username_email
    methods:
        request_header:
            enabled: true
        request_body:
            enabled: false
        cookie:
            enabled: false